application: antiochwp-a
version: wpproject
runtime: php55
api_version: 0.8.6
instance_class: F4
threadsafe: true


handlers:

# begin Multisite handlers
- url: /wp-admin/network/(.+)
  script: wordpress/wp-admin/network/\1
  login: required
#  secure: always

- url: /wp-admin/network/
  script: wordpress/wp-admin/network/index.php
  login: required
#  secure: always

- url: /([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*\.(htm.*$|html.*$|css.*$|js.*$|ico.*$|jpg.*$|png.*$|gif.*$))
  static_files: wordpress/\2
  upload: wordpress/([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*\.(htm.*$|html.*$|css.*$|js.*$|ico.*$|jpg.*$|png.*$|gif.*$))
  application_readable: true
# end Multisite handlers

## Add additional handlers for every site you add ## start
- url: /digest/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /digest/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /digest/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always
  
#add 2016patomos (2016.7.7) ---------------------
- url: /2016patmos/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /2016patmos/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /2016patmos/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

#add music (2016.7.30) -------------------------
- url: /music/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /music/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /music/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

#add testimony (2016.8.13) ---------------------
- url: /testimony/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /testimony/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /testimony/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

#add 201609cambodia (2016.9.15) ---------------------
- url: /201609cambodia/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /201609cambodia/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /201609cambodia/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

#add 2016israel360 (2016.11.1) ---------------------
- url: /2016israel360/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /2016israel360/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /2016israel360/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

#add 16israel360tour (2016.11.23) ---------------------
- url: /16israel360tour/wp-admin/(.+)
  script: wordpress/wp-admin/\1
#  secure: always
  login: required

- url: /16israel360tour/wp-admin/ 
  script: wordpress/wp-admin/index.php
#  secure: always
  login: required
  
- url: /16israel360tour/wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

## ## end/ Add additional handlers for every site you add 

- url: /(.*\.(htm|html|css|js))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(htm|html|css|js)$
  application_readable: true

- url: /wp-content/(.*\.(ico|jpg|png|gif))$
  static_files: wordpress/wp-content/\1
  upload: wordpress/wp-content/.*\.(ico|jpg|png|gif)$
  application_readable: true

- url: /(.*\.(ico|jpg|png|gif|svg))$
  static_files: wordpress/\1
  upload: wordpress/.*\.(ico|jpg|png|gif|svg)$

- url: /wp-admin/(.+)
  script: wordpress/wp-admin/\1
  login: required
#  secure: always

- url: /wp-admin/
  script: wordpress/wp-admin/index.php
  login: required
#  secure: always

- url: /wp-login.php
  script: wordpress/wp-login.php
  login: required
#  secure: always

- url: /wp-cron.php
  script: wordpress/wp-cron.php
  login: admin

- url: /wp-(.+).php
  script: wordpress/wp-\1.php

- url: /(.+)?/?
  script: wordpress/index.php

# スマホアプリなどの管理画面アクセス
- url: /xmlrpc.php
# script: wordpress/xmlrpc.php
# redirect4dos.html 経由でリダイレクトさせてアクセス不許可
  upload: redirect4dos.html
  static_files: redirect4dos.html

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- wordpress/wp-content/uploads/.*
